name: 'Show input'
description: 'Parse body'

inputs:
  OUT1:
    required: true
  OUT2:
    required: false
    default: OUT-DEFAULT
    
runs:
  using: composite
  steps:
    - name: Show
      shell: bash
      run: |
        echo ${{ inputs.OUT1 }}
        echo ${{ inputs.OUT2 }}
        echo ${{ inputs.OUT3 }}
        echo ${INPUT_OUT1}
        echo ${INPUT_OUT2}
        echo ${INPUT_OUT3}
    
    - name: Show JS
      uses: actions/github-script@v7
       
      with:
        OUT1: ${{ inputs.OUT1 }}
        OUT2: ${{ inputs.OUT2 }}
        script: |
          console.log("1:" +core.getInput('OUT1'));
          console.log("2:" +core.getInput('OUT2'));
          console.log("3:" +core.getInput('OUT3'));
      
