name: Output
on:
  workflow_dispatch:

jobs:
  out:
    name: Check output
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: step1
        run: |
          echo "OUT1=FIRST" >> "$GITHUB_OUTPUT"
          echo "::set-output name=OUT1::SECOND"

          echo "::set-output name=OUT2::FIRST"
          echo "OUT2=SECOND" >> "$GITHUB_OUTPUT"
          echo "coucou Bearer token"

      - name: Show output
        run: |
          echo "::set-output name=NOPE::FIRST"
          echo ${{ steps.step1.outputs.OUT1 }}
          echo ${{ steps.step1.outputs.OUT2 }}
